<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/OwlCarousel2-2.3.4/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/OwlCarousel2-2.3.4/owl.theme.default.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/bootstrap-select.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugin/intl-tel-input/build/css/intlTelInput.css') }}">
<link rel="stylesheet" href="{{ asset('css/sb-admin-2.css') }}">
<link rel="stylesheet" href="{{ asset('css/style.css') }}">
<link rel="stylesheet" href="{{ asset('css/responsive.css') }}">
